# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import matplotlib
matplotlib.use('Qt5Agg')

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        self.clicksCount = 0
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 852)
        MainWindow.setStyleSheet("background-color: rgb(216, 227, 231);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(940, 30, 309, 99))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.constant = QtWidgets.QLabel(self.centralwidget)
        self.constant.setGeometry(QtCore.QRect(930, 190, 331, 221))
        self.constant.setText("")
        self.constant.setPixmap(QtGui.QPixmap("constant.png"))
        self.constant.setScaledContents(True)
        self.constant.setObjectName("constant")
        self.ballsetting = QtWidgets.QLabel(self.centralwidget)
        self.ballsetting.setGeometry(QtCore.QRect(930, 430, 331, 201))
        self.ballsetting.setText("")
        self.ballsetting.setPixmap(QtGui.QPixmap("ballset.png"))
        self.ballsetting.setScaledContents(True)
        self.ballsetting.setObjectName("ballsetting")

        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(930, 700, 151, 71))
        self.start.setStyleSheet("background-color: rgb(18, 110, 130);\n"
                                 "font: 57 28pt \"Mazzard Soft M Med\";")
        self.start.setObjectName("start")
        self.start.setCheckable(False)
        self.start.toggle()
        self.start.clicked.connect(self.update_chart)

        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(1110, 700, 151, 71))
        self.reset.setStyleSheet("background-color: rgb(18, 110, 130);\n"
                                 "font: 57 28pt \"Mazzard Soft M Med\";")
        self.reset.setObjectName("reset")
        self.graphlogo = QtWidgets.QLabel(self.centralwidget)
        self.graphlogo.setGeometry(QtCore.QRect(20, 20, 671, 67))
        self.graphlogo.setText("")
        self.graphlogo.setPixmap(QtGui.QPixmap("Graphlogo.png"))
        self.graphlogo.setScaledContents(True)
        self.graphlogo.setObjectName("graphlogo")
        self.Audit = QtWidgets.QPushButton(self.centralwidget)
        self.Audit.setGeometry(QtCore.QRect(690, 20, 181, 68))
        self.Audit.setStyleSheet("background-color: rgb(81, 196, 211);\n"
        "font: 57 28pt \"Mazzard Soft M SemBd\";")
        self.Audit.setObjectName("Audit")

        self.Position = QtWidgets.QLabel(self.centralwidget)
        self.Position.setGeometry(QtCore.QRect(20, 490, 331, 111))
        self.Position.setText("")
        self.Position.setPixmap(QtGui.QPixmap("Position.png"))
        self.Position.setScaledContents(True)
        self.Position.setObjectName("Position")
        self.posx = QtWidgets.QTextBrowser(self.centralwidget)
        self.posx.setGeometry(QtCore.QRect(80, 550, 71, 31))
        self.posx.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
        "background-color: rgb(19, 44, 51);")
        self.posx.setObjectName("posx")
        self.posy = QtWidgets.QTextBrowser(self.centralwidget)
        self.posy.setGeometry(QtCore.QRect(240, 550, 71, 31))
        self.posy.setStyleSheet("font: 57 18pt \"Mazzard Soft M Med\";\n"
        "border-color: rgb(19, 44, 51);\n"
"background-color: rgb(19, 44, 51);")
        self.posy.setObjectName("posy")
        self.Output = QtWidgets.QLabel(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(20, 620, 331, 161))
        self.Output.setText("")
        self.Output.setPixmap(QtGui.QPixmap("Output.png"))
        self.Output.setScaledContents(True)
        self.Output.setObjectName("Output")
        self.velo = QtWidgets.QTextBrowser(self.centralwidget)
        self.velo.setGeometry(QtCore.QRect(240, 690, 101, 35))
        self.velo.setStyleSheet("font: 57 18pt \"Mazzard Soft M Med\";\n"
"border-color: rgb(19, 44, 51);\n"
"background-color: rgb(19, 44, 51);")
        self.velo.setObjectName("velo")
        self.findis = QtWidgets.QTextBrowser(self.centralwidget)
        self.findis.setGeometry(QtCore.QRect(240, 730, 101, 31))
        self.findis.setStyleSheet("font: 57 18pt \"Mazzard Soft M Med\";\n"
"border-color: rgb(19, 44, 51);\n"
"background-color: rgb(19, 44, 51);")
        self.findis.setObjectName("findis")

        self.recoil = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.recoil.setGeometry(QtCore.QRect(1100, 490, 151, 61))
        self.recoil.setStyleSheet("background-color: rgb(81, 196, 211);\n"
"font: 57 14pt \"Mazzard Soft M Med\";")
        self.recoil.setObjectName("recoil")
        hx = 5
        self.recoil.setValue(hx)

        self.recoil_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.recoil_2.setGeometry(QtCore.QRect(1100, 550, 151, 61))
        self.recoil_2.setStyleSheet("background-color: rgb(81, 196, 211);\n"
"font: 57 14pt \"Mazzard Soft M Med\";")
        self.recoil_2.setObjectName("recoil_2")
        go = 2.5
        self.recoil_2.setValue(go)

        self.patseq = QtWidgets.QLabel(self.centralwidget)
        self.patseq.setGeometry(QtCore.QRect(430, 490, 400, 138))
        self.patseq.setText("")
        self.patseq.setPixmap(QtGui.QPixmap("patseq.png"))
        self.patseq.setScaledContents(True)
        self.patseq.setObjectName("patseq")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(430, 640, 401, 141))
        self.result.setText("")
        self.result.setPixmap(QtGui.QPixmap("Result.png"))
        self.result.setScaledContents(True)
        self.result.setObjectName("result")
        self.pathres1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.pathres1.setGeometry(QtCore.QRect(730, 690, 100, 25))
        self.pathres1.setStyleSheet("background-color: rgb(19, 44, 51);\n"
"font: 57 14pt \"Mazzard Soft M Med\";")
        self.pathres1.setObjectName("pathres1")
        self.pathres2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.pathres2.setGeometry(QtCore.QRect(730, 720, 100, 25))
        self.pathres2.setStyleSheet("background-color: rgb(19, 44, 51);\n"
"font: 57 14pt \"Mazzard Soft M Med\";")
        self.pathres2.setObjectName("pathres2")
        self.pathres3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.pathres3.setGeometry(QtCore.QRect(730, 750, 100, 25))
        self.pathres3.setStyleSheet("background-color: rgb(19, 44, 51);\n"
"font: 57 14pt \"Mazzard Soft M Med\";")
        self.pathres3.setObjectName("pathres3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1345, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.layout = QtWidgets.QVBoxLayout()
        self.layout.setContentsMargins(0, 0, 0, 0)

        self.GG = QtWidgets.QVBoxLayout(self.centralwidget)
        self.GG.setContentsMargins(20,0, 0, 270)
        self.canvas = FigureCanvas(plt.Figure(figsize=(100, 9), dpi=50))
        self.canvas.setFixedSize(850,380)
        self.GG.addWidget(self.canvas)
        self.insert_ax()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def insert_ax(self):
        font = {
            'weight': 'normal',
            'size': 24
        }
        matplotlib.rc('font', **font)

        self.ax = self.canvas.figure.subplots()
        self.ax.set_ylim([0.55, 0.7])
        self.ax.set_xlim([0, 3])

        x2 = [0.0, 3.0]
        y2 = [0.6, 0.6]
        x3 = [2.5, 2.5]
        y3 = [0.5, 1.5]
        self.ax.plot(x2, y2)
        self.ax.plot(x3, y3)
        self.bar = None

    def update_chart(self):
        value = self.recoil.value()
        value2 = self.recoil_2.value()
        if value > 15 or value < 0:
            return
        if value2 > 4 or value2 < 2.5:
            return
        self.clicksCount += 1
        _translate = QtCore.QCoreApplication.translate
        value = float(value) / 100
        v = 5.14
        g = 9.81  # improved g to standard precision, set it to positive
        h = value + 0.04 + 0.02
        #print(h)
        m = 0.024 + 0.045
        # increment theta 25 to 60 then find  t, x, y
        # define x and y as arrays
        theta = 45 / 180.0 * np.pi  # convert to radians, watch out for modulo division
        plt.figure()
        tmax = ((2.1 * v) * np.sin(theta))/g
        timemat = tmax * np.linspace(0, 1, 150)[:, None]  # create time vectors for each angle
        x = (((v * timemat)) * (value2/2.8)*np.cos(theta))
        y = ((((m * v * timemat) * np.sin(theta)) - ((0.5 * (m * g) + (-h / 5)) * (timemat ** 2)))) + 0.6
        #self.posx.display(x[-1][0])
        #self.posx.append("{0} = <a>".format(x[-1][0]))

        #self.posy.display(y[-1][0])
        #self.findis.display(x[-1][0])
        #self.findis.update()

        #self.velo.display(v)
        #self.velo.update()

        print(x[-1][0])
        print(y[-1][0])
        print(v)
        self.posx.append("<span>goodbye</span>")
        if self.clicksCount == 1:
            self.posx.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.52</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
            self.posy.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">0.60</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
            self.posy.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">0.60</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))

            if x[-1][0] > 2.3 and x[-1][0] < 2.7 and y[-1][0] > 0.6 and y[-1][0] < 0.605:
                self.pathres1.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaff00;\">goal</span></p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#aaff00;\"><br /></p></body></html>"))

            else:
                self.pathres1.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">fail</span></p></body></html>"))

        if self.clicksCount == 2:
            self.posx.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.53</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
            self.posy.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">0.61</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
            self.findis.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:18pt; font-weight:56; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ffffff;\">-m</span></p>\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#ffffff;\"><br /></p></body></html>"))

            if x[-1][0] > 2.3 and x[-1][0] < 2.7 and y[-1][0] > 0.6 and y[-1][0] < 0.605:
                self.pathres2.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaff00;\">goal</span></p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#aaff00;\"><br /></p></body></html>"))

            else:
                self.pathres2.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">fail</span></p></body></html>"))

        if self.clicksCount == 3:
            self.posx.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">2.53</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))

            self.posy.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:16pt; font-weight:56; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">0.62</span></p>\n"
                                         "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
            self.findis.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:18pt; font-weight:56; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ffffff;\">-m</span></p>\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#ffffff;\"><br /></p></body></html>"))

            if x[-1][0] > 2.3 and x[-1][0] < 2.7 and y[-1][0] > 0.6 and y[-1][0] < 0.605:
                self.pathres3.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                             "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaff00;\">goal</span></p>\n"
                                             "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#aaff00;\"><br /></p></body></html>"))

            else:
                self.pathres3.setHtml(_translate("MainWindow",
                                             "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                             "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                             "p, li { white-space: pre-wrap; }\n"
                                             "</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
                                             "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">fail</span></p></body></html>"))


        print(self.clicksCount)
        if self.clicksCount == 4:
            self.ax.cla()
            self.ax.set_ylim([0.55, 0.7])
            self.ax.set_xlim([0, 3])
            self.clicksCount = 0
            self.insert_ax()
        if self.bar:
            self.bar.remove()
        self.ax.plot(x, y)
        self.canvas.draw()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Start</span></p></body></html>"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.reset.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Reset</span></p></body></html>"))
        self.reset.setText(_translate("MainWindow", "Member"))
        self.Audit.setText(_translate("MainWindow", "Audit log"))
        self.posx.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>001</p></body></html>"))
        self.posx.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">001</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.posy.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>002</p></body></html>"))
        self.posy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:18pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">002</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
        self.velo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">002</span></p></body></html>"))
        self.velo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:18pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ffffff;\">5.14m/s</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#ffffff;\"><br /></p></body></html>"))
        self.findis.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">002</span></p></body></html>"))
        self.findis.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:18pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#ffffff;\">2.5m</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; color:#ffffff;\"><br /></p></body></html>"))

        self.recoil.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">0.01</span></p></body></html>"))
        self.recoil.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">005</span></p></body></html>"))
        self.recoil_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">0.01</span></p></body></html>"))
        self.pathres1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaff00;\">goal</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#aaff00;\"><br /></p></body></html>"))
        self.pathres2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">fail</span></p></body></html>"))
        self.pathres3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:14pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#aaff00;\">goal</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
