# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiaudit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(QtWidgets.QMainWindow):
    def setupUi(self, Dialog):
        Dialog.setObjectName("member")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(19, 44, 51);")
        self.reset = QtWidgets.QPushButton(Dialog)
        self.reset.setGeometry(QtCore.QRect(480, 370, 141, 51))
        self.reset.setStyleSheet("background-color: rgb(18, 110, 130);\n"
"font: 57 28pt \"Mazzard Soft M Med\";")
        self.reset.setObjectName("reset")
        self.auditloggo = QtWidgets.QLabel(Dialog)
        self.auditloggo.setGeometry(QtCore.QRect(0, 0, 641, 61))
        self.auditloggo.setText("")
        self.auditloggo.setPixmap(QtGui.QPixmap("auditlogo.png"))
        self.auditloggo.setScaledContents(True)
        self.auditloggo.setObjectName("auditloggo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 60, 661, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("audittop.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.time = QtWidgets.QTextBrowser(Dialog)
        self.time.setGeometry(QtCore.QRect(20, 140, 81, 31))
        self.time.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.time.setObjectName("time")
        self.coil = QtWidgets.QTextBrowser(Dialog)
        self.coil.setGeometry(QtCore.QRect(140, 140, 131, 31))
        self.coil.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.coil.setObjectName("coil")
        self.dist = QtWidgets.QTextBrowser(Dialog)
        self.dist.setGeometry(QtCore.QRect(320, 140, 161, 31))
        self.dist.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.dist.setObjectName("dist")
        self.res = QtWidgets.QTextBrowser(Dialog)
        self.res.setGeometry(QtCore.QRect(520, 140, 91, 31))
        self.res.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.res.setObjectName("res")
        self.time_2 = QtWidgets.QTextBrowser(Dialog)
        self.time_2.setGeometry(QtCore.QRect(20, 190, 81, 31))
        self.time_2.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.time_2.setObjectName("time_2")
        self.coil_2 = QtWidgets.QTextBrowser(Dialog)
        self.coil_2.setGeometry(QtCore.QRect(140, 190, 131, 31))
        self.coil_2.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.coil_2.setObjectName("coil_2")
        self.dist_2 = QtWidgets.QTextBrowser(Dialog)
        self.dist_2.setGeometry(QtCore.QRect(320, 190, 161, 31))
        self.dist_2.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.dist_2.setObjectName("dist_2")
        self.res_2 = QtWidgets.QTextBrowser(Dialog)
        self.res_2.setGeometry(QtCore.QRect(520, 190, 91, 31))
        self.res_2.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.res_2.setObjectName("res_2")
        self.time_3 = QtWidgets.QTextBrowser(Dialog)
        self.time_3.setGeometry(QtCore.QRect(20, 240, 81, 31))
        self.time_3.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.time_3.setObjectName("time_3")
        self.coil_3 = QtWidgets.QTextBrowser(Dialog)
        self.coil_3.setGeometry(QtCore.QRect(140, 240, 131, 31))
        self.coil_3.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.coil_3.setObjectName("coil_3")
        self.dist_3 = QtWidgets.QTextBrowser(Dialog)
        self.dist_3.setGeometry(QtCore.QRect(320, 240, 161, 31))
        self.dist_3.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.dist_3.setObjectName("dist_3")
        self.res_3 = QtWidgets.QTextBrowser(Dialog)
        self.res_3.setGeometry(QtCore.QRect(520, 240, 91, 31))
        self.res_3.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.res_3.setObjectName("res_3")
        self.time_4 = QtWidgets.QTextBrowser(Dialog)
        self.time_4.setGeometry(QtCore.QRect(20, 290, 81, 31))
        self.time_4.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.time_4.setObjectName("time_4")
        self.coil_4 = QtWidgets.QTextBrowser(Dialog)
        self.coil_4.setGeometry(QtCore.QRect(140, 290, 131, 31))
        self.coil_4.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.coil_4.setObjectName("coil_4")
        self.dist_4 = QtWidgets.QTextBrowser(Dialog)
        self.dist_4.setGeometry(QtCore.QRect(320, 290, 161, 31))
        self.dist_4.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.dist_4.setObjectName("dist_4")
        self.res_4 = QtWidgets.QTextBrowser(Dialog)
        self.res_4.setGeometry(QtCore.QRect(520, 290, 91, 31))
        self.res_4.setStyleSheet("font: 57 11pt \"Mazzard Soft M Med\";\n"
"background-color: rgb(19, 44, 51);")
        self.res_4.setObjectName("res_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.reset.setToolTip(_translate("Dialog", "<html><head/><body><p>return</p><p><br/></p></body></html>"))
        self.reset.setWhatsThis(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffffff;\">Reset</span></p></body></html>"))
        self.reset.setText(_translate("Dialog", "Return"))
        self.time.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.time.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">16:55</span></p></body></html>"))
        self.coil.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.coil.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.dist.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.dist.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">2.5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.res.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.res.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">goal</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.time_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.time_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">16:55</span></p></body></html>"))
        self.coil_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.coil_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">10</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.dist_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.dist_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">2.5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.res_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.res_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">fail</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.time_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.time_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">16:55</span></p></body></html>"))
        self.coil_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.coil_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">15</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.dist_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.dist_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">2.5</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.res_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.res_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">fail</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.time_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.time_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; color:#ffffff;\">16:55</span></p></body></html>"))
        self.coil_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.coil_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">001</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.dist_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.dist_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">001</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))
        self.res_4.setWhatsThis(_translate("Dialog", "<html><head/><body><p>001</p></body></html>"))
        self.res_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Mazzard Soft M Med\'; font-size:11pt; font-weight:56; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">001</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt; color:#ffffff;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
